---
# tasks file for slack-notification
# publish message to slack to update status
# Make sure to include this role in your requirments.yml file for Tower to pull
# ie: roles/requirments.yml
#
#
#- debug:
#    msg: "MyToken: {{ slack_token }}"

- name: Send notification message via Slack
  slack:
    # To retrieve your slack token, open your team settings and look for the
    token: "{{ slack_token }}"
    msg: "{{ slack_message }}"
    icon_url: "{{ slack_icon }}"
    channel: "{{ slack_channel }}"
    username: "{{ slack_username }}"
    color: "{{ slack_color }}"
